package com.srx.dao.srx_gpl_dao;

import com.srx.model.srx_gpl_model.Policiesandregulations;
import com.srx.model.srx_gpl_model.PoliciesandregulationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoliciesandregulationsMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	long countByExample(PoliciesandregulationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	int deleteByExample(PoliciesandregulationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	int insert(Policiesandregulations record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	int insertSelective(Policiesandregulations record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	List<Policiesandregulations> selectByExample(PoliciesandregulationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	Policiesandregulations selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Policiesandregulations record,
			@Param("example") PoliciesandregulationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	int updateByExample(@Param("record") Policiesandregulations record,
			@Param("example") PoliciesandregulationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	int updateByPrimaryKeySelective(Policiesandregulations record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table policiesandregulations
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	int updateByPrimaryKey(Policiesandregulations record);

	List lt();
	
	List lt_content(Integer id);
}