package com.srx.model.srx_gpl_model;

public class Policiesandregulations {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column policiesandregulations.id
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column policiesandregulations.name
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column policiesandregulations.content
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column policiesandregulations.id
	 * @return  the value of policiesandregulations.id
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column policiesandregulations.id
	 * @param id  the value for policiesandregulations.id
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column policiesandregulations.name
	 * @return  the value of policiesandregulations.name
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column policiesandregulations.name
	 * @param name  the value for policiesandregulations.name
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column policiesandregulations.content
	 * @return  the value of policiesandregulations.content
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column policiesandregulations.content
	 * @param content  the value for policiesandregulations.content
	 * @mbg.generated  Fri Dec 06 10:35:15 CST 2019
	 */
	public void setContent(String content) {
		this.content = content;
	}

	@Override
	public String toString() {
		return "Policiesandregulations [id=" + id + ", name=" + name + ", content=" + content + "]";
	}

}