package com.srx.model.srx_fyl_model;

public class Introduction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.sid
     *
     * @mbg.generated Wed Dec 04 15:08:46 CST 2019
     */
    private Integer iid;

    
	public Integer getIid() {
		return iid;
	}
	public void setIid(Integer iid) {
		this.iid = iid;
	}
	public String getIname() {
		return iname;
	}
	public void setIname(String iname) {
		this.iname = iname;
	}
	public String getIintroduction() {
		return iintroduction;
	}
	public void setIintroduction(String iintroduction) {
		this.iintroduction = iintroduction;
	}
	public Integer getIclick() {
		return iclick;
	}
	public void setIclick(Integer iclick) {
		this.iclick = iclick;
	}
	public String getIimg() {
		return iimg;
	}
	public void setIimg(String iimg) {
		this.iimg = iimg;
	}
	public Integer getTid() {
		return tid;
	}
	public void setTid(Integer tid) {
		this.tid = tid;
	}
	public String getTname() {
		return tname;
	}
	public void setTname(String tname) {
		this.tname = tname;
	}
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.sname
     *
     * @mbg.generated Wed Dec 04 15:08:46 CST 2019
     */
    private String iname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.sintroduction
     *
     * @mbg.generated Wed Dec 04 15:08:46 CST 2019
     */
    private String iintroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.sclick
     *
     * @mbg.generated Wed Dec 04 15:08:46 CST 2019
     */
    private Integer iclick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.simg
     *
     * @mbg.generated Wed Dec 04 15:08:46 CST 2019
     */
    private String iimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.tid
     *
     * @mbg.generated Wed Dec 04 15:08:46 CST 2019
     */
    private Integer tid;
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.sid
     *
     * @return the value of introduction.sid
     *
     * @mbg.generated Wed Dec 04 15:08:46 CST 2019
     */
   
}