package com.srx.model.srx_fyl_model;

public class Zj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj.zjid
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    private Integer zjid;
    

    public Integer getYhid() {
		return yhid;
	}

	public void setYhid(Integer yhid) {
		this.yhid = yhid;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj.zjcontent
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    private String zjcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj.zjtime
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    private String zjtime;
    private Integer yhid;


	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zj.iid
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    private Integer iid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj.zjid
     *
     * @return the value of zj.zjid
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    public Integer getZjid() {
        return zjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj.zjid
     *
     * @param zjid the value for zj.zjid
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    public void setZjid(Integer zjid) {
        this.zjid = zjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj.zjcontent
     *
     * @return the value of zj.zjcontent
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    public String getZjcontent() {
        return zjcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj.zjcontent
     *
     * @param zjcontent the value for zj.zjcontent
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    public void setZjcontent(String zjcontent) {
        this.zjcontent = zjcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj.zjtime
     *
     * @return the value of zj.zjtime
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    public String getZjtime() {
        return zjtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj.zjtime
     *
     * @param zjtime the value for zj.zjtime
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    public void setZjtime(String zjtime) {
        this.zjtime = zjtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zj.iid
     *
     * @return the value of zj.iid
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zj.iid
     *
     * @param iid the value for zj.iid
     *
     * @mbg.generated Tue Dec 10 20:02:58 CST 2019
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }


    
}