package com.srx.dao.srx_mzj_dao;

import com.srx.model.srx_mzj_model.Menuitem;
import com.srx.model.srx_mzj_model.MenuitemExample;
import com.srx.model.srx_mzj_model.Type;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    long countByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    int deleteByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    int insert(Menuitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    int insertSelective(Menuitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    List<Menuitem> selectByExample(MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    Menuitem selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") Menuitem record, @Param("example") MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    int updateByExample(@Param("record") Menuitem record, @Param("example") MenuitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    int updateByPrimaryKeySelective(Menuitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    int updateByPrimaryKey(Menuitem record);
    List<Menuitem> selMenuitem();
}