package com.srx.dao.srx_mzj_dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srx.model.srx_mzj_model.Video;
import com.srx.model.srx_mzj_model.VideoExample;

public interface VideoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	long countByExample(VideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	int deleteByExample(VideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	int deleteByPrimaryKey(Integer vid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	int insertSelective(Video record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	List<Video> selectByExample(VideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	Video selectByPrimaryKey(Integer vid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Video record, @Param("example") VideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	int updateByExample(@Param("record") Video record, @Param("example") VideoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	int updateByPrimaryKeySelective(Video record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table video
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	int updateByPrimaryKey(Video record);

	List<Video> sel();/* ��ѯ��Ƶ */

	List<Video> selvideo(Integer id);// ������ ��ѯ
	
	List<Video> selectLikeVtitle(String vtitle);//ck搜索

	List<Video> selectAll();
	
	 /*查询视频 MZJ*/
		List<Video> selvideoPC(String iidp);
		
		/*添加视频 WYL*/
		int insert(Video record);

	 
}