package com.srx.dao.srx_fzk_dao;

import com.srx.model.srx_fzk_model.Advertisement;
import com.srx.model.srx_fzk_model.AdvertisementExample;
import com.srx.model.srx_fzk_model.Videolist;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvertisementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    long countByExample(AdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    int deleteByExample(AdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    int insert(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    int insertSelective(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    List<Advertisement> selectByExample(AdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    Advertisement selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") Advertisement record, @Param("example") AdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    int updateByExample(@Param("record") Advertisement record, @Param("example") AdvertisementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    int updateByPrimaryKeySelective(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    int updateByPrimaryKey(Advertisement record);
    
    //查询所有广告
	List<Advertisement> selectAll();
	//根据专家编号查询所有视频
	List<Advertisement> selectVideo(Integer id);
	//根据视频热度查询视频
	List<Videolist> selectTopvideo();
}