package com.srx.dao.srx_fzk_dao;

import com.srx.model.srx_fyl_model.UserAnwser;
import com.srx.model.srx_fzk_model.UserInteraction;
import com.srx.model.srx_fzk_model.UserInteractionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInteractionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    long countByExample(UserInteractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    int deleteByExample(UserInteractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    int insert(UserInteraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    int insertSelective(UserInteraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    List<UserInteraction> selectByExample(UserInteractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    UserInteraction selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserInteraction record, @Param("example") UserInteractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    int updateByExample(@Param("record") UserInteraction record, @Param("example") UserInteractionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    int updateByPrimaryKeySelective(UserInteraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_interaction
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    int updateByPrimaryKey(UserInteraction record);
    
	/* 把用户互动信息传入数据库 */
    int insertdata(UserInteraction ui);
	
    /* 查询用户互动信息 */
    List<UserInteraction> getuserdate(int vid);
    //回复用户互动信息
    int insertuser(UserAnwser user);
    //查询用户回复信息
    List<UserAnwser> sel_user(int id);
    
}