package com.srx.model.srx_fzk_model;

import java.sql.Date;

public class Advertisement {
	//作者姓名
	private String iname;
	
	//作者简介
	private String iintroduction;
	
	//作者
	private String iimg;
	
	//视频ID
	private int vid;
	
	//视频发布时间
	private Date vdate;
	
	//视频热度
	private int vclicks;
	
	//视频路径
	private String vurl;
	
	//视频简介
	private String vtitle;
	
	//视频图片
	private String vpicture;

	public String getVpicture() {
		return vpicture;
	}

	public void setVpicture(String vpicture) {
		this.vpicture = vpicture;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.aid
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.aurl
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    private String apicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.avideo
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    private String avideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.atitle
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    private String atitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.iid
     *
     * @mbg.generated Thu Dec 05 10:58:28 CST 2019
     */
    private Integer iid;

	public String getIname() {
		return iname;
	}

	public void setIname(String iname) {
		this.iname = iname;
	}

	public String getIintroduction() {
		return iintroduction;
	}

	public void setIintroduction(String iintroduction) {
		this.iintroduction = iintroduction;
	}

	public int getVid() {
		return vid;
	}

	public void setVid(int vid) {
		this.vid = vid;
	}

	public Date getVdate() {
		return vdate;
	}

	public void setVdate(Date vdate) {
		this.vdate = vdate;
	}

	public int getVclicks() {
		return vclicks;
	}

	public void setVclicks(int vclicks) {
		this.vclicks = vclicks;
	}

	public String getVurl() {
		return vurl;
	}

	public void setVurl(String vurl) {
		this.vurl = vurl;
	}

	public Integer getAid() {
		return aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public String getAurl() {
		return apicture;
	}

	public void setAurl(String aurl) {
		this.apicture = aurl;
	}

	public String getAvideo() {
		return avideo;
	}

	public void setAvideo(String avideo) {
		this.avideo = avideo;
	}

	public String getAtitle() {
		return atitle;
	}

	public void setAtitle(String atitle) {
		this.atitle = atitle;
	}

	public Integer getIid() {
		return iid;
	}

	public void setIid(Integer iid) {
		this.iid = iid;
	}

	public String getIimg() {
		return iimg;
	}

	public void setIimg(String iimg) {
		this.iimg = iimg;
	}

	public String getVtitle() {
		return vtitle;
	}

	public void setVtitle(String vtitle) {
		this.vtitle = vtitle;
	}

	@Override
	public String toString() {
		return "Advertisement [iname=" + iname + ", iintroduction=" + iintroduction + ", iimg=" + iimg + ", vid=" + vid
				+ ", vdate=" + vdate + ", vclicks=" + vclicks + ", vurl=" + vurl + ", vtitle=" + vtitle + ", vpicture="
				+ vpicture + ", aid=" + aid + ", apicture=" + apicture + ", avideo=" + avideo + ", atitle=" + atitle
				+ ", iid=" + iid + "]";
	}


	
}