package com.srx.model.srx_fzk_model;

import java.text.SimpleDateFormat;
import java.util.Date;

public class UserInteraction {
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_interaction.uuid
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    private Integer uuid;
    
    //专家ID
    private Integer iid;
    //视频ID   
    private Integer vid;



	@Override
	public String toString() {
		return "UserInteraction [uuid=" + uuid + ", iid=" + iid + ", vid=" + vid + ", uname=" + uname + ", ucontent="
				+ ucontent + ", udate=" + udate + ", upraise=" + upraise + ", ustatusid=" + ustatusid + "]";
	}

	public Integer getUuid() {
		return uuid;
	}

	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	public Integer getIid() {
		return iid;
	}

	public void setIid(Integer iid) {
		this.iid = iid;
	}

	public Integer getVid() {
		return vid;
	}

	public void setVid(Integer vid) {
		this.vid = vid;
	}

	public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUcontent() {
		return ucontent;
	}

	public void setUcontent(String ucontent) {
		this.ucontent = ucontent;
	}

	public Date getUdate() {
		return udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	public Integer getUpraise() {
		return upraise;
	}

	public void setUpraise(Integer upraise) {
		this.upraise = upraise;
	}

	public Integer getUstatusid() {
		return ustatusid;
	}

	public void setUstatusid(Integer ustatusid) {
		this.ustatusid = ustatusid;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_interaction.uname
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_interaction.ucontent
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    private String ucontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_interaction.udate
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    private Date udate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_interaction.upraise
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    private Integer upraise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_interaction.userid
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
    private Integer ustatusid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_interaction.uuid
     *
     * @return the value of user_interaction.uuid
     *
     * @mbg.generated Tue Dec 24 09:15:28 CST 2019
     */
  



}