package com.srx.model.srx_mzj_model;

public class Introduction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.iid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    private Integer iid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.iname
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    private String iname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.iintroduction
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    private String iintroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.iclick
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    private Integer iclick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.iimg
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    private String iimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.tid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.tpwd
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    private String tpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introduction.tuid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    private String tuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.iid
     *
     * @return the value of introduction.iid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introduction.iid
     *
     * @param iid the value for introduction.iid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.iname
     *
     * @return the value of introduction.iname
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public String getIname() {
        return iname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introduction.iname
     *
     * @param iname the value for introduction.iname
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public void setIname(String iname) {
        this.iname = iname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.iintroduction
     *
     * @return the value of introduction.iintroduction
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public String getIintroduction() {
        return iintroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introduction.iintroduction
     *
     * @param iintroduction the value for introduction.iintroduction
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public void setIintroduction(String iintroduction) {
        this.iintroduction = iintroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.iclick
     *
     * @return the value of introduction.iclick
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public Integer getIclick() {
        return iclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introduction.iclick
     *
     * @param iclick the value for introduction.iclick
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public void setIclick(Integer iclick) {
        this.iclick = iclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.iimg
     *
     * @return the value of introduction.iimg
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public String getIimg() {
        return iimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introduction.iimg
     *
     * @param iimg the value for introduction.iimg
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public void setIimg(String iimg) {
        this.iimg = iimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.tid
     *
     * @return the value of introduction.tid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introduction.tid
     *
     * @param tid the value for introduction.tid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.tpwd
     *
     * @return the value of introduction.tpwd
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public String getTpwd() {
        return tpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introduction.tpwd
     *
     * @param tpwd the value for introduction.tpwd
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public void setTpwd(String tpwd) {
        this.tpwd = tpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introduction.tuid
     *
     * @return the value of introduction.tuid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public String getTuid() {
        return tuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introduction.tuid
     *
     * @param tuid the value for introduction.tuid
     *
     * @mbg.generated Tue Dec 24 17:02:13 CST 2019
     */
    public void setTuid(String tuid) {
        this.tuid = tuid;
    }
}