package com.srx.model.srx_mzj_model;

public class Menuitem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.mid
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.mtitle
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    private String mtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.murl
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    private String murl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem.mhref
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    private String mhref;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.mid
     *
     * @return the value of menuitem.mid
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.mid
     *
     * @param mid the value for menuitem.mid
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.mtitle
     *
     * @return the value of menuitem.mtitle
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    public String getMtitle() {
        return mtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.mtitle
     *
     * @param mtitle the value for menuitem.mtitle
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    public void setMtitle(String mtitle) {
        this.mtitle = mtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.murl
     *
     * @return the value of menuitem.murl
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    public String getMurl() {
        return murl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.murl
     *
     * @param murl the value for menuitem.murl
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    public void setMurl(String murl) {
        this.murl = murl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem.mhref
     *
     * @return the value of menuitem.mhref
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    public String getMhref() {
        return mhref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem.mhref
     *
     * @param mhref the value for menuitem.mhref
     *
     * @mbg.generated Thu Dec 05 19:21:07 CST 2019
     */
    public void setMhref(String mhref) {
        this.mhref = mhref;
    }
}