package com.srx.model.srx_mzj_model;

public class Type {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.tid
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.tname
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.ticon
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    private String ticon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.tid
     *
     * @return the value of type.tid
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.tid
     *
     * @param tid the value for type.tid
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.tname
     *
     * @return the value of type.tname
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.tname
     *
     * @param tname the value for type.tname
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.ticon
     *
     * @return the value of type.ticon
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    public String getTicon() {
        return ticon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.ticon
     *
     * @param ticon the value for type.ticon
     *
     * @mbg.generated Thu Dec 05 08:36:32 CST 2019
     */
    public void setTicon(String ticon) {
        this.ticon = ticon;
    }
}