package com.srx.model.srx_mzj_model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VideoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public VideoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andVidIsNull() {
            addCriterion("vid is null");
            return (Criteria) this;
        }

        public Criteria andVidIsNotNull() {
            addCriterion("vid is not null");
            return (Criteria) this;
        }

        public Criteria andVidEqualTo(Integer value) {
            addCriterion("vid =", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotEqualTo(Integer value) {
            addCriterion("vid <>", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThan(Integer value) {
            addCriterion("vid >", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThanOrEqualTo(Integer value) {
            addCriterion("vid >=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThan(Integer value) {
            addCriterion("vid <", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThanOrEqualTo(Integer value) {
            addCriterion("vid <=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidIn(List<Integer> values) {
            addCriterion("vid in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotIn(List<Integer> values) {
            addCriterion("vid not in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidBetween(Integer value1, Integer value2) {
            addCriterion("vid between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotBetween(Integer value1, Integer value2) {
            addCriterion("vid not between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVtitleIsNull() {
            addCriterion("vtitle is null");
            return (Criteria) this;
        }

        public Criteria andVtitleIsNotNull() {
            addCriterion("vtitle is not null");
            return (Criteria) this;
        }

        public Criteria andVtitleEqualTo(String value) {
            addCriterion("vtitle =", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleNotEqualTo(String value) {
            addCriterion("vtitle <>", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleGreaterThan(String value) {
            addCriterion("vtitle >", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleGreaterThanOrEqualTo(String value) {
            addCriterion("vtitle >=", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleLessThan(String value) {
            addCriterion("vtitle <", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleLessThanOrEqualTo(String value) {
            addCriterion("vtitle <=", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleLike(String value) {
            addCriterion("vtitle like", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleNotLike(String value) {
            addCriterion("vtitle not like", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleIn(List<String> values) {
            addCriterion("vtitle in", values, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleNotIn(List<String> values) {
            addCriterion("vtitle not in", values, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleBetween(String value1, String value2) {
            addCriterion("vtitle between", value1, value2, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleNotBetween(String value1, String value2) {
            addCriterion("vtitle not between", value1, value2, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVdateIsNull() {
            addCriterion("vdate is null");
            return (Criteria) this;
        }

        public Criteria andVdateIsNotNull() {
            addCriterion("vdate is not null");
            return (Criteria) this;
        }

        public Criteria andVdateEqualTo(Date value) {
            addCriterionForJDBCDate("vdate =", value, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("vdate <>", value, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateGreaterThan(Date value) {
            addCriterionForJDBCDate("vdate >", value, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vdate >=", value, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateLessThan(Date value) {
            addCriterionForJDBCDate("vdate <", value, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("vdate <=", value, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateIn(List<Date> values) {
            addCriterionForJDBCDate("vdate in", values, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("vdate not in", values, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vdate between", value1, value2, "vdate");
            return (Criteria) this;
        }

        public Criteria andVdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("vdate not between", value1, value2, "vdate");
            return (Criteria) this;
        }

        public Criteria andVclicksIsNull() {
            addCriterion("vclicks is null");
            return (Criteria) this;
        }

        public Criteria andVclicksIsNotNull() {
            addCriterion("vclicks is not null");
            return (Criteria) this;
        }

        public Criteria andVclicksEqualTo(Integer value) {
            addCriterion("vclicks =", value, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksNotEqualTo(Integer value) {
            addCriterion("vclicks <>", value, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksGreaterThan(Integer value) {
            addCriterion("vclicks >", value, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksGreaterThanOrEqualTo(Integer value) {
            addCriterion("vclicks >=", value, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksLessThan(Integer value) {
            addCriterion("vclicks <", value, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksLessThanOrEqualTo(Integer value) {
            addCriterion("vclicks <=", value, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksIn(List<Integer> values) {
            addCriterion("vclicks in", values, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksNotIn(List<Integer> values) {
            addCriterion("vclicks not in", values, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksBetween(Integer value1, Integer value2) {
            addCriterion("vclicks between", value1, value2, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVclicksNotBetween(Integer value1, Integer value2) {
            addCriterion("vclicks not between", value1, value2, "vclicks");
            return (Criteria) this;
        }

        public Criteria andVurlIsNull() {
            addCriterion("vurl is null");
            return (Criteria) this;
        }

        public Criteria andVurlIsNotNull() {
            addCriterion("vurl is not null");
            return (Criteria) this;
        }

        public Criteria andVurlEqualTo(String value) {
            addCriterion("vurl =", value, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlNotEqualTo(String value) {
            addCriterion("vurl <>", value, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlGreaterThan(String value) {
            addCriterion("vurl >", value, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlGreaterThanOrEqualTo(String value) {
            addCriterion("vurl >=", value, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlLessThan(String value) {
            addCriterion("vurl <", value, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlLessThanOrEqualTo(String value) {
            addCriterion("vurl <=", value, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlLike(String value) {
            addCriterion("vurl like", value, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlNotLike(String value) {
            addCriterion("vurl not like", value, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlIn(List<String> values) {
            addCriterion("vurl in", values, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlNotIn(List<String> values) {
            addCriterion("vurl not in", values, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlBetween(String value1, String value2) {
            addCriterion("vurl between", value1, value2, "vurl");
            return (Criteria) this;
        }

        public Criteria andVurlNotBetween(String value1, String value2) {
            addCriterion("vurl not between", value1, value2, "vurl");
            return (Criteria) this;
        }

        public Criteria andVpictureIsNull() {
            addCriterion("vpicture is null");
            return (Criteria) this;
        }

        public Criteria andVpictureIsNotNull() {
            addCriterion("vpicture is not null");
            return (Criteria) this;
        }

        public Criteria andVpictureEqualTo(String value) {
            addCriterion("vpicture =", value, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureNotEqualTo(String value) {
            addCriterion("vpicture <>", value, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureGreaterThan(String value) {
            addCriterion("vpicture >", value, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureGreaterThanOrEqualTo(String value) {
            addCriterion("vpicture >=", value, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureLessThan(String value) {
            addCriterion("vpicture <", value, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureLessThanOrEqualTo(String value) {
            addCriterion("vpicture <=", value, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureLike(String value) {
            addCriterion("vpicture like", value, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureNotLike(String value) {
            addCriterion("vpicture not like", value, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureIn(List<String> values) {
            addCriterion("vpicture in", values, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureNotIn(List<String> values) {
            addCriterion("vpicture not in", values, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureBetween(String value1, String value2) {
            addCriterion("vpicture between", value1, value2, "vpicture");
            return (Criteria) this;
        }

        public Criteria andVpictureNotBetween(String value1, String value2) {
            addCriterion("vpicture not between", value1, value2, "vpicture");
            return (Criteria) this;
        }

        public Criteria andIidIsNull() {
            addCriterion("iid is null");
            return (Criteria) this;
        }

        public Criteria andIidIsNotNull() {
            addCriterion("iid is not null");
            return (Criteria) this;
        }

        public Criteria andIidEqualTo(Integer value) {
            addCriterion("iid =", value, "iid");
            return (Criteria) this;
        }

        public Criteria andIidNotEqualTo(Integer value) {
            addCriterion("iid <>", value, "iid");
            return (Criteria) this;
        }

        public Criteria andIidGreaterThan(Integer value) {
            addCriterion("iid >", value, "iid");
            return (Criteria) this;
        }

        public Criteria andIidGreaterThanOrEqualTo(Integer value) {
            addCriterion("iid >=", value, "iid");
            return (Criteria) this;
        }

        public Criteria andIidLessThan(Integer value) {
            addCriterion("iid <", value, "iid");
            return (Criteria) this;
        }

        public Criteria andIidLessThanOrEqualTo(Integer value) {
            addCriterion("iid <=", value, "iid");
            return (Criteria) this;
        }

        public Criteria andIidIn(List<Integer> values) {
            addCriterion("iid in", values, "iid");
            return (Criteria) this;
        }

        public Criteria andIidNotIn(List<Integer> values) {
            addCriterion("iid not in", values, "iid");
            return (Criteria) this;
        }

        public Criteria andIidBetween(Integer value1, Integer value2) {
            addCriterion("iid between", value1, value2, "iid");
            return (Criteria) this;
        }

        public Criteria andIidNotBetween(Integer value1, Integer value2) {
            addCriterion("iid not between", value1, value2, "iid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 05 20:16:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated Thu Dec 05 20:16:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}