package com.srx.model.srx_mzj_model;

import java.sql.Date;

public class Video {
	/**
	 *===
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column video.vid
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	private Integer vid;

	public Integer getVid() {
		return vid;
	}

	public void setVid(Integer vid) {
		this.vid = vid;
	}

	public String getVtitle() {
		return vtitle;
	}

	public void setVtitle(String vtitle) {
		this.vtitle = vtitle;
	}

	public Date getVdate() {
		return vdate;
	}

	public void setVdate(Date vdate) {
		this.vdate = vdate;
	}

	public Integer getVclicks() {
		return vclicks;
	}

	public void setVclicks(Integer vclicks) {
		this.vclicks = vclicks;
	}

	public String getVurl() {
		return vurl;
	}

	public void setVurl(String vurl) {
		this.vurl = vurl;
	}

	public String getVpicture() {
		return vpicture;
	}

	public void setVpicture(String vpicture) {
		this.vpicture = vpicture;
	}

	public Integer getIid() {
		return iid;
	}

	public void setIid(Integer iid) {
		this.iid = iid;
	}

	public Integer getTid() {
		return tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public String getTname() {
		return tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public String getTicon() {
		return ticon;
	}

	public void setTicon(String ticon) {
		this.ticon = ticon;
	}

	public String getIname() {
		return iname;
	}

	public void setIname(String iname) {
		this.iname = iname;
	}

	public String getIintroduction() {
		return iintroduction;
	}

	public void setIintroduction(String iintroduction) {
		this.iintroduction = iintroduction;
	}

	public Integer getIclick() {
		return iclick;
	}

	public void setIclick(Integer iclick) {
		this.iclick = iclick;
	}

	public String getIimg() {
		return iimg;
	}

	public void setIimg(String iimg) {
		this.iimg = iimg;
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column video.vtitle
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	private String vtitle;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column video.vdate
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	private Date vdate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column video.vclicks
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	private Integer vclicks;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column video.vurl
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	private String vurl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column video.vpicture
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	private String vpicture;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column video.iid
	 *
	 * @mbg.generated Thu Dec 05 20:16:23 CST 2019
	 */
	private Integer iid;
	private Integer tid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column type.tname
	 *
	 * @mbg.generated Thu Dec 05 08:36:32 CST 2019
	 */
	private String tname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column type.ticon
	 *
	 * @mbg.generated Thu Dec 05 08:36:32 CST 2019
	 */
	private String ticon;
	private String iname;
	private String iintroduction;
	private Integer iclick;
	private String iimg;

	@Override
	public String toString() {
		return "Video [vid=" + vid + ", vtitle=" + vtitle + ", vdate=" + vdate + ", vclicks=" + vclicks + ", vurl="
				+ vurl + ", vpicture=" + vpicture + ", iid=" + iid + ", tid=" + tid + ", tname=" + tname + ", ticon="
				+ ticon + ", iname=" + iname + ", iintroduction=" + iintroduction + ", iclick=" + iclick + ", iimg="
				+ iimg + "]";
	}

	public void setVdate(java.util.Date date1) {
		// TODO Auto-generated method stub
		
	}


	

}